### ISSUE TITLE
Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms

### ISSUE THREAD

**Issue by opportunistic** [rarible/ethereum-indexer-public#491]
Getting this problem on the https://api.rarible.org/v0.1/items/byOwner endpoint on around 2/3 requests, not sure if it is due to load on that server or what.  Might take a stab at running my own instance of this API.  Full error below:

`Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms; nested exception is reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms`

Additionally, I've noticed that there's some huge inconsistencies in the results between the API used on the Rarible website, the `/v0.1/items/byOwner` endpoint with the `V1` search engine and the `LEGACY` search engine.  I've seen assets that were transferred away from someone over a year ago still listed as being under their ownership (on rarible.org), so I'm not quite sure what that's all about.  I'll see if I can get you guys some examples.

I have noticed that `/v0.1/items/byOwner` with the `V1` search engine returns the best results by far.

**Comment by opportunistic** [comment]
Actually, this looks like it's for the gateway API?  I'm not sure if this is applicable to this project.

**Comment by evgenynacu** [comment]
Closing this issue as stale
This should be fixed 

Feel free to reopen if needed
