### ISSUE TITLE
The indexer crashes after 20 mins.

### ISSUE THREAD

**Issue by jessebowd** [rarible/ethereum-indexer-public#57]
Hi,
I got the a small part of the indexer to work, but after 20mins-1hr running, it crashes.

Connections to Mongo gets a Timeout and the NFT Listener stops working.

What is the recommended setup for the mongo instance and the application?

Also, how long does it take to index the NFT data?

**Comment by AnjanaKavinda** [comment]
HI, @jessebowd  I also set up and build the project and currently I'm trying to run the nft -> api [protocol-nft-indexer-api] service.
But there is a error like "java.lang.NullPointerException: Parameter specified as non-null is null: method com.rarible.protocol.nft.api.configuration.NftIndexerApiProperties., parameter operator".
if you are already fixed this kind of error, please let us know how did you solve the issue.

**Comment by evgenynacu** [comment]
Closing this as stale
Feel free to reopen if needed
